### ISSUE TITLE
Wrong GPS coordinates format

### ISSUE THREAD

**Issue by aurelbdx** [sbeuh34/NeoFlyTouristTour#1]
Bonjour,
 je me permets de parler en français car apparemment tu parles français également :)
J'ai ce message d'erreur quand je clique sur "create mission" : Wrong GPS coordinates format
Je me demande si ce n'est pas un problème avec les virgules (symbole décimal dans les options "Horloge et région" de windows)
On avait eu ce problème à une époque avec NeoFly

sur la capture dans les coordonnées on peut voir des points et des virgules d'où le problème
https://www.dropbox.com/s/wucv6aux4b5zl6i/2021-01-20_00-47-34.png?dl=0

Si je remplace manuellement les points par des virgules je n'ai plus la fenêtre Bad format mais j'ai ceci:
https://www.dropbox.com/s/188kchcqd3kej24/2.png?dl=0

**Comment by sbeuh34** [comment]
Fixed with package 1.0.1
