### ISSUE TITLE
message d'erreur suite à la mise à jour 1.0.1

### ISSUE THREAD

**Issue by aurelbdx** [sbeuh34/NeoFlyTouristTour#2]
Bonjour, 
suite à la mise à jour, quand je clique sur "Create mission" j'ai cette fenêtre qui apparait:
https://www.dropbox.com/s/188kchcqd3kej24/2.png?dl=0
si je clique sur continuer, aucun changement et si je clique sur quitter ça ferme NeoFlyTouristTour

**Comment by sbeuh34** [comment]
Bonjour,

Je n'arrive pas à reproduire ce problème de mon côté. Pouvez vous me copier les données brutes que vous saisissez dans les différents champs de l'application? ainsi qu'un Screenshots avant de cliquer sur "Create mission".

**Comment by aurelbdx** [comment]
je rentre comme donnée "49.455471, 10.854114" puis je clique sur "create mission" uniquement
https://www.dropbox.com/s/15m99q502tdwaq0/2021-01-21_20-12-45.png?dl=0

pour info voila le message d'erreur:

System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.Double.Parse(String s)
   à NeoFlyTouristTour.Form1.btn_create_Click(Object sender, EventArgs e) dans C:\Users\sbeuh\source\repos\NeoFlyTouristTour\NeoFlyTouristTour\Form1.cs:ligne 144
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

C'est normal que j'ai ça dedans ?
C:\Users\sbeuh\source\repos\NeoFlyTouristTour\NeoFlyTouristTour\Form1.cs:ligne 144

**Comment by sbeuh34** [comment]
Thanks for feedback.
Resolved in v1.0.3.
Give it a try please.

**Comment by aurelbdx** [comment]
Merci, maintenant ça fonctionne très bien!
Serait-t-il possible d'avoir le nom du POI plutôt que "tourist requested POI" ?
